
/**
 * this file is generated by autogen.sh, do NOT modify it.
 */

#include "native.h"

#include "out/sun/reflect/Reflection.h"
#include "out/java/io/FileOutputStream.h"
#include "out/java/io/FileDescriptor.h"
#include "out/java/io/FileInputStream.h"
#include "out/java/lang/Float.h"
#include "out/java/lang/Thread.h"
#include "out/java/lang/Class.h"
#include "out/java/lang/Object.h"
#include "out/java/lang/System.h"
#include "out/java/lang/String.h"


constexpr java_native_method_t java_native_methods[] = {
    { "Java_sun_reflect_Reflection_getCallerClass__", (void*) Java_sun_reflect_Reflection_getCallerClass__ },
    { "Java_sun_reflect_Reflection_getCallerClass__I", (void*) Java_sun_reflect_Reflection_getCallerClass__I },
    { "Java_sun_reflect_Reflection_getClassAccessFlags", (void*) Java_sun_reflect_Reflection_getClassAccessFlags },

    { "Java_java_io_FileOutputStream_close0", (void*) Java_java_io_FileOutputStream_close0 },
    { "Java_java_io_FileOutputStream_initIDs", (void*) Java_java_io_FileOutputStream_initIDs },
    { "Java_java_io_FileOutputStream_open0", (void*) Java_java_io_FileOutputStream_open0 },
    { "Java_java_io_FileOutputStream_writeBytes", (void*) Java_java_io_FileOutputStream_writeBytes },

    { "Java_java_io_FileDescriptor_sync", (void*) Java_java_io_FileDescriptor_sync },

    { "Java_java_io_FileInputStream_available0", (void*) Java_java_io_FileInputStream_available0 },
    { "Java_java_io_FileInputStream_close0", (void*) Java_java_io_FileInputStream_close0 },
    { "Java_java_io_FileInputStream_initIDs", (void*) Java_java_io_FileInputStream_initIDs },
    { "Java_java_io_FileInputStream_open0", (void*) Java_java_io_FileInputStream_open0 },
    { "Java_java_io_FileInputStream_readBytes", (void*) Java_java_io_FileInputStream_readBytes },
    { "Java_java_io_FileInputStream_skip0", (void*) Java_java_io_FileInputStream_skip0 },

    { "Java_java_lang_Float_floatToRawIntBits", (void*) Java_java_lang_Float_floatToRawIntBits },
    { "Java_java_lang_Float_intBitsToFloat", (void*) Java_java_lang_Float_intBitsToFloat },

    { "Java_java_lang_Thread_currentThread", (void*) Java_java_lang_Thread_currentThread },
    { "Java_java_lang_Thread_dumpThreads", (void*) Java_java_lang_Thread_dumpThreads },
    { "Java_java_lang_Thread_getThreads", (void*) Java_java_lang_Thread_getThreads },
    { "Java_java_lang_Thread_holdsLock", (void*) Java_java_lang_Thread_holdsLock },
    { "Java_java_lang_Thread_interrupt0", (void*) Java_java_lang_Thread_interrupt0 },
    { "Java_java_lang_Thread_isInterrupted", (void*) Java_java_lang_Thread_isInterrupted },
    { "Java_java_lang_Thread_registerNatives", (void*) Java_java_lang_Thread_registerNatives },
    { "Java_java_lang_Thread_setNativeName", (void*) Java_java_lang_Thread_setNativeName },
    { "Java_java_lang_Thread_setPriority0", (void*) Java_java_lang_Thread_setPriority0 },
    { "Java_java_lang_Thread_sleep", (void*) Java_java_lang_Thread_sleep },
    { "Java_java_lang_Thread_start0", (void*) Java_java_lang_Thread_start0 },
    { "Java_java_lang_Thread_yield", (void*) Java_java_lang_Thread_yield },

    { "Java_java_lang_Class_desiredAssertionStatus0", (void*) Java_java_lang_Class_desiredAssertionStatus0 },
    { "Java_java_lang_Class_forName0", (void*) Java_java_lang_Class_forName0 },
    { "Java_java_lang_Class_getAnnotatedInterfaces", (void*) Java_java_lang_Class_getAnnotatedInterfaces },
    { "Java_java_lang_Class_getAnnotatedSuperclass", (void*) Java_java_lang_Class_getAnnotatedSuperclass },
    { "Java_java_lang_Class_getAnnotation", (void*) Java_java_lang_Class_getAnnotation },
    { "Java_java_lang_Class_getAnnotations", (void*) Java_java_lang_Class_getAnnotations },
    { "Java_java_lang_Class_getAnnotationsByType", (void*) Java_java_lang_Class_getAnnotationsByType },
    { "Java_java_lang_Class_getClassLoader0", (void*) Java_java_lang_Class_getClassLoader0 },
    { "Java_java_lang_Class_getClasses0", (void*) Java_java_lang_Class_getClasses0 },
    { "Java_java_lang_Class_getComponentType", (void*) Java_java_lang_Class_getComponentType },
    { "Java_java_lang_Class_getConstructor0", (void*) Java_java_lang_Class_getConstructor0 },
    { "Java_java_lang_Class_getConstructors0", (void*) Java_java_lang_Class_getConstructors0 },
    { "Java_java_lang_Class_getDeclaredAnnotation", (void*) Java_java_lang_Class_getDeclaredAnnotation },
    { "Java_java_lang_Class_getDeclaredAnnotations", (void*) Java_java_lang_Class_getDeclaredAnnotations },
    { "Java_java_lang_Class_getDeclaredAnnotationsByType", (void*) Java_java_lang_Class_getDeclaredAnnotationsByType },
    { "Java_java_lang_Class_getDeclaredClasses0", (void*) Java_java_lang_Class_getDeclaredClasses0 },
    { "Java_java_lang_Class_getDeclaredConstructor0", (void*) Java_java_lang_Class_getDeclaredConstructor0 },
    { "Java_java_lang_Class_getDeclaredConstructors0", (void*) Java_java_lang_Class_getDeclaredConstructors0 },
    { "Java_java_lang_Class_getDeclaredField0", (void*) Java_java_lang_Class_getDeclaredField0 },
    { "Java_java_lang_Class_getDeclaredFields0", (void*) Java_java_lang_Class_getDeclaredFields0 },
    { "Java_java_lang_Class_getDeclaredMethod0", (void*) Java_java_lang_Class_getDeclaredMethod0 },
    { "Java_java_lang_Class_getDeclaredMethods0", (void*) Java_java_lang_Class_getDeclaredMethods0 },
    { "Java_java_lang_Class_getDeclaringClass0", (void*) Java_java_lang_Class_getDeclaringClass0 },
    { "Java_java_lang_Class_getEnclosingClass", (void*) Java_java_lang_Class_getEnclosingClass },
    { "Java_java_lang_Class_getEnclosingConstructor", (void*) Java_java_lang_Class_getEnclosingConstructor },
    { "Java_java_lang_Class_getEnclosingMethod", (void*) Java_java_lang_Class_getEnclosingMethod },
    { "Java_java_lang_Class_getField0", (void*) Java_java_lang_Class_getField0 },
    { "Java_java_lang_Class_getFields0", (void*) Java_java_lang_Class_getFields0 },
    { "Java_java_lang_Class_getGenericInterfaces", (void*) Java_java_lang_Class_getGenericInterfaces },
    { "Java_java_lang_Class_getGenericSuperclass", (void*) Java_java_lang_Class_getGenericSuperclass },
    { "Java_java_lang_Class_getInterfaces", (void*) Java_java_lang_Class_getInterfaces },
    { "Java_java_lang_Class_getMethod0", (void*) Java_java_lang_Class_getMethod0 },
    { "Java_java_lang_Class_getMethods0", (void*) Java_java_lang_Class_getMethods0 },
    { "Java_java_lang_Class_getModifiers0", (void*) Java_java_lang_Class_getModifiers0 },
    { "Java_java_lang_Class_getName0", (void*) Java_java_lang_Class_getName0 },
    { "Java_java_lang_Class_getPrimitiveClass", (void*) Java_java_lang_Class_getPrimitiveClass },
    { "Java_java_lang_Class_getSuperclass", (void*) Java_java_lang_Class_getSuperclass },
    { "Java_java_lang_Class_getTypeParameters", (void*) Java_java_lang_Class_getTypeParameters },
    { "Java_java_lang_Class_isArray", (void*) Java_java_lang_Class_isArray },
    { "Java_java_lang_Class_isAssignableFrom", (void*) Java_java_lang_Class_isAssignableFrom },
    { "Java_java_lang_Class_isInstance", (void*) Java_java_lang_Class_isInstance },
    { "Java_java_lang_Class_isPrimitive", (void*) Java_java_lang_Class_isPrimitive },
    { "Java_java_lang_Class_newInstance0", (void*) Java_java_lang_Class_newInstance0 },

    { "Java_java_lang_Object_clone", (void*) Java_java_lang_Object_clone },
    { "Java_java_lang_Object_getClass", (void*) Java_java_lang_Object_getClass },
    { "Java_java_lang_Object_notify", (void*) Java_java_lang_Object_notify },
    { "Java_java_lang_Object_notifyAll", (void*) Java_java_lang_Object_notifyAll },
    { "Java_java_lang_Object_wait", (void*) Java_java_lang_Object_wait },

    { "Java_java_lang_System_arraycopy", (void*) Java_java_lang_System_arraycopy },
    { "Java_java_lang_System_currentTimeMillis", (void*) Java_java_lang_System_currentTimeMillis },
    { "Java_java_lang_System_identityHashCode", (void*) Java_java_lang_System_identityHashCode },
    { "Java_java_lang_System_initProperties", (void*) Java_java_lang_System_initProperties },
    { "Java_java_lang_System_mapLibraryName", (void*) Java_java_lang_System_mapLibraryName },
    { "Java_java_lang_System_nanoTime", (void*) Java_java_lang_System_nanoTime },
    { "Java_java_lang_System_setErr0", (void*) Java_java_lang_System_setErr0 },
    { "Java_java_lang_System_setIn0", (void*) Java_java_lang_System_setIn0 },
    { "Java_java_lang_System_setOut0", (void*) Java_java_lang_System_setOut0 },

    { "Java_java_lang_String_intern", (void*) Java_java_lang_String_intern },

    { nullptr, nullptr }, 
};
