
/**
 * this file is generated by autogen.sh, do NOT modify it.
 */

#include "native.h"

#include "out/java/io/FileOutputStream.h"
#include "out/java/io/FileDescriptor.h"
#include "out/java/io/FileInputStream.h"
#include "out/java/lang/Class.h"
#include "out/java/lang/Object.h"
#include "out/java/lang/System.h"
#include "out/java/lang/String.h"


constexpr java_native_method_t java_native_methods[] = {
    { "java/io/FileOutputStream", "close0", "()V", (void*) Java_java_io_FileOutputStream_close0 },
    { "java/io/FileOutputStream", "initIDs", "()V", (void*) Java_java_io_FileOutputStream_initIDs },
    { "java/io/FileOutputStream", "open0", "(Ljava/lang/String;Z)V", (void*) Java_java_io_FileOutputStream_open0 },
    { "java/io/FileOutputStream", "write", "(IZ)V", (void*) Java_java_io_FileOutputStream_write },
    { "java/io/FileOutputStream", "writeBytes", "([BIIZ)V", (void*) Java_java_io_FileOutputStream_writeBytes },

    { "java/io/FileDescriptor", "sync", "()V", (void*) Java_java_io_FileDescriptor_sync },

    { "java/io/FileInputStream", "available0", "()I", (void*) Java_java_io_FileInputStream_available0 },
    { "java/io/FileInputStream", "close0", "()V", (void*) Java_java_io_FileInputStream_close0 },
    { "java/io/FileInputStream", "initIDs", "()V", (void*) Java_java_io_FileInputStream_initIDs },
    { "java/io/FileInputStream", "open0", "(Ljava/lang/String;)V", (void*) Java_java_io_FileInputStream_open0 },
    { "java/io/FileInputStream", "readBytes", "([BII)I", (void*) Java_java_io_FileInputStream_readBytes },
    { "java/io/FileInputStream", "skip0", "(J)J", (void*) Java_java_io_FileInputStream_skip0 },

    { "java/lang/Class", "desiredAssertionStatus0", "(Ljava/lang/Class;)Z", (void*) Java_java_lang_Class_desiredAssertionStatus0 },
    { "java/lang/Class", "forName0", "(Ljava/lang/String;ZLjava/lang/ClassLoader;Ljava/lang/Class;)Ljava/lang/Class;", (void*) Java_java_lang_Class_forName0 },
    { "java/lang/Class", "getAnnotatedInterfaces", "()[Ljava/lang/reflect/AnnotatedType;", (void*) Java_java_lang_Class_getAnnotatedInterfaces },
    { "java/lang/Class", "getAnnotatedSuperclass", "()Ljava/lang/reflect/AnnotatedType;", (void*) Java_java_lang_Class_getAnnotatedSuperclass },
    { "java/lang/Class", "getAnnotation", "(Ljava/lang/Class;)Ljava/lang/annotation/Annotation;", (void*) Java_java_lang_Class_getAnnotation },
    { "java/lang/Class", "getAnnotations", "()[Ljava/lang/annotation/Annotation;", (void*) Java_java_lang_Class_getAnnotations },
    { "java/lang/Class", "getAnnotationsByType", "(Ljava/lang/Class;)[Ljava/lang/annotation/Annotation;", (void*) Java_java_lang_Class_getAnnotationsByType },
    { "java/lang/Class", "getClassLoader0", "()Ljava/lang/ClassLoader;", (void*) Java_java_lang_Class_getClassLoader0 },
    { "java/lang/Class", "getClasses0", "()[Ljava/lang/Class;", (void*) Java_java_lang_Class_getClasses0 },
    { "java/lang/Class", "getComponentType", "()Ljava/lang/Class;", (void*) Java_java_lang_Class_getComponentType },
    { "java/lang/Class", "getConstructor0", "([Ljava/lang/Class;)Ljava/lang/reflect/Constructor;", (void*) Java_java_lang_Class_getConstructor0 },
    { "java/lang/Class", "getConstructors0", "()[Ljava/lang/reflect/Constructor;", (void*) Java_java_lang_Class_getConstructors0 },
    { "java/lang/Class", "getDeclaredAnnotation", "(Ljava/lang/Class;)Ljava/lang/annotation/Annotation;", (void*) Java_java_lang_Class_getDeclaredAnnotation },
    { "java/lang/Class", "getDeclaredAnnotations", "()[Ljava/lang/annotation/Annotation;", (void*) Java_java_lang_Class_getDeclaredAnnotations },
    { "java/lang/Class", "getDeclaredAnnotationsByType", "(Ljava/lang/Class;)[Ljava/lang/annotation/Annotation;", (void*) Java_java_lang_Class_getDeclaredAnnotationsByType },
    { "java/lang/Class", "getDeclaredClasses0", "()[Ljava/lang/Class;", (void*) Java_java_lang_Class_getDeclaredClasses0 },
    { "java/lang/Class", "getDeclaredConstructor0", "([Ljava/lang/Class;)Ljava/lang/reflect/Constructor;", (void*) Java_java_lang_Class_getDeclaredConstructor0 },
    { "java/lang/Class", "getDeclaredConstructors0", "()[Ljava/lang/reflect/Constructor;", (void*) Java_java_lang_Class_getDeclaredConstructors0 },
    { "java/lang/Class", "getDeclaredField0", "(Ljava/lang/String;)Ljava/lang/reflect/Field;", (void*) Java_java_lang_Class_getDeclaredField0 },
    { "java/lang/Class", "getDeclaredFields0", "()[Ljava/lang/reflect/Field;", (void*) Java_java_lang_Class_getDeclaredFields0 },
    { "java/lang/Class", "getDeclaredMethod0", "(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;", (void*) Java_java_lang_Class_getDeclaredMethod0 },
    { "java/lang/Class", "getDeclaredMethods0", "()[Ljava/lang/reflect/Method;", (void*) Java_java_lang_Class_getDeclaredMethods0 },
    { "java/lang/Class", "getDeclaringClass0", "()Ljava/lang/Class;", (void*) Java_java_lang_Class_getDeclaringClass0 },
    { "java/lang/Class", "getEnclosingClass", "()Ljava/lang/Class;", (void*) Java_java_lang_Class_getEnclosingClass },
    { "java/lang/Class", "getEnclosingConstructor", "()Ljava/lang/reflect/Constructor;", (void*) Java_java_lang_Class_getEnclosingConstructor },
    { "java/lang/Class", "getEnclosingMethod", "()Ljava/lang/reflect/Method;", (void*) Java_java_lang_Class_getEnclosingMethod },
    { "java/lang/Class", "getField0", "(Ljava/lang/String;)Ljava/lang/reflect/Field;", (void*) Java_java_lang_Class_getField0 },
    { "java/lang/Class", "getFields0", "()[Ljava/lang/reflect/Field;", (void*) Java_java_lang_Class_getFields0 },
    { "java/lang/Class", "getGenericInterfaces", "()[Ljava/lang/reflect/Type;", (void*) Java_java_lang_Class_getGenericInterfaces },
    { "java/lang/Class", "getGenericSuperclass", "()Ljava/lang/reflect/Type;", (void*) Java_java_lang_Class_getGenericSuperclass },
    { "java/lang/Class", "getInterfaces", "()[Ljava/lang/Class;", (void*) Java_java_lang_Class_getInterfaces },
    { "java/lang/Class", "getMethod0", "(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;", (void*) Java_java_lang_Class_getMethod0 },
    { "java/lang/Class", "getMethods0", "()[Ljava/lang/reflect/Method;", (void*) Java_java_lang_Class_getMethods0 },
    { "java/lang/Class", "getModifiers0", "()I", (void*) Java_java_lang_Class_getModifiers0 },
    { "java/lang/Class", "getName0", "()Ljava/lang/String;", (void*) Java_java_lang_Class_getName0 },
    { "java/lang/Class", "getPrimitiveClass", "(Ljava/lang/String;)Ljava/lang/Class;", (void*) Java_java_lang_Class_getPrimitiveClass },
    { "java/lang/Class", "getSuperclass", "()Ljava/lang/Class;", (void*) Java_java_lang_Class_getSuperclass },
    { "java/lang/Class", "getTypeParameters", "()[Ljava/lang/reflect/TypeVariable;", (void*) Java_java_lang_Class_getTypeParameters },
    { "java/lang/Class", "isArray", "()Z", (void*) Java_java_lang_Class_isArray },
    { "java/lang/Class", "isAssignableFrom", "(Ljava/lang/Class;)Z", (void*) Java_java_lang_Class_isAssignableFrom },
    { "java/lang/Class", "isInstance", "(Ljava/lang/Object;)Z", (void*) Java_java_lang_Class_isInstance },
    { "java/lang/Class", "isPrimitive", "()Z", (void*) Java_java_lang_Class_isPrimitive },

    { "java/lang/Object", "clone", "()Ljava/lang/Object;", (void*) Java_java_lang_Object_clone },
    { "java/lang/Object", "getClass", "()Ljava/lang/Class;", (void*) Java_java_lang_Object_getClass },
    { "java/lang/Object", "notify", "()V", (void*) Java_java_lang_Object_notify },
    { "java/lang/Object", "notifyAll", "()V", (void*) Java_java_lang_Object_notifyAll },
    { "java/lang/Object", "wait", "(J)V", (void*) Java_java_lang_Object_wait },

    { "java/lang/System", "arraycopy", "(Ljava/lang/Object;ILjava/lang/Object;II)V", (void*) Java_java_lang_System_arraycopy },
    { "java/lang/System", "currentTimeMillis", "()J", (void*) Java_java_lang_System_currentTimeMillis },
    { "java/lang/System", "identityHashCode", "(Ljava/lang/Object;)I", (void*) Java_java_lang_System_identityHashCode },
    { "java/lang/System", "initProperties", "(Ljava/util/Properties;)Ljava/util/Properties;", (void*) Java_java_lang_System_initProperties },
    { "java/lang/System", "mapLibraryName", "(Ljava/lang/String;)Ljava/lang/String;", (void*) Java_java_lang_System_mapLibraryName },
    { "java/lang/System", "nanoTime", "()J", (void*) Java_java_lang_System_nanoTime },
    { "java/lang/System", "setErr0", "(Ljava/io/PrintStream;)V", (void*) Java_java_lang_System_setErr0 },
    { "java/lang/System", "setIn0", "(Ljava/io/InputStream;)V", (void*) Java_java_lang_System_setIn0 },
    { "java/lang/System", "setOut0", "(Ljava/io/PrintStream;)V", (void*) Java_java_lang_System_setOut0 },

    { "java/lang/String", "intern", "()Ljava/lang/String;", (void*) Java_java_lang_String_intern },

    { nullptr, nullptr, nullptr, nullptr }, 
};
