/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native */

#ifndef _Included_Native
#define _Included_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native
 * Method:    nAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Native_nAdd__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Native
 * Method:    nAdd
 * Signature: (ZBCSIJFDZBCSIJFD)D
 */
JNIEXPORT jdouble JNICALL Java_Native_nAdd__ZBCSIJFDZBCSIJFD
  (JNIEnv *, jclass, jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble);

#ifdef __cplusplus
}
#endif
#endif
